---
title: "Bacillus heat profiles"
author: "Jasmine Ahmed and Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin = 2.54cm
---

# Microcalorimetry of Bacillus subtilis delta 6 on different media

# Clear workspace and set directory

```{r setup}
rm(list = ls())
knitr::opts_knit$set(root.dir=normalizePath("~/Github/symcel"))
getwd()
```

## Load packages and functions

```{r}
require("png")
require("dplyr")
library("tidyverse")
require("grid")
require("tibble")
require("knitr")
require("extrafont")
require("ggrepel");
require("gridExtra")
require("contrast")
require("purrr")
sem <- function(x) sqrt(var(x)/length(x))
cv <- function(x) (sd(x)/mean(x))*100
```

# Load data

```{r}
data.raw <- read.csv("~/Github/symcel/data/20240329csvheatflow.csv")
design <- read.csv("~/Github/symcel/data/designfile20240411heatflow.csv")
```

# Change time

```{r}
# Change times to numeric (hours)
time.s <- as.numeric(sub("^(\\d+):(\\d+).*", "\\1.\\2", data.raw[,1]))
colnames(data.raw)[colnames(data.raw) == "Time..s."] <- "time"
```


# Time-averaging to reduce size of data frame

```{r}
# Define size of interval
observations_per_interval <- 5 * 60 / 4  # 5 min, 60 sec/min, 4 sec per observation

# Function to average a vector over each interval
average_over_interval <- function(data_vector) {
  time_index <- rep(1:(ceiling(length(data_vector) / observations_per_interval)), 
    each = observations_per_interval, length.out = length(data_vector))
  averaged_values <- tapply(data_vector, time_index, mean)
  #return(averaged_values[time_index])
  return(averaged_values)
}

averaged_data <- lapply(data.raw, average_over_interval)
data <- as.data.frame(averaged_data)

time.h <- data[,1]/60/60
```


# Create look-up table

```{r}
# This code chunk reads in the experimental design file
# Converts 96-well plate layout into long form
# Then creates column number reference number

# Subset the design file
media <- design[1:6,1:8]
wells <- design[7:12,1:8]

# convert 96 well plate format to long format
media.long <- as.data.frame(pivot_longer(media, cols = everything(), 
              names_to = "Treatment", values_to = "Value"))
wells.long <- as.data.frame(pivot_longer(wells, cols = everything(), 
              names_to = "Treatment", values_to = "Value"))

# Create vector of column numbers
col.vect <- seq(1, 48)

# Combine into one look up table
look.table <- data.frame(media.long[,2], wells.long[,2], col.vect)
colnames(look.table) <- c("media", "well", "col")
```


# Pull out wells by treatment and make data frames

```{r}
# Following code pulls out vector of column numbers corresponding to a medium
# Then creates a data frame with time and ODs
# Need to add one (+1) because of how time in read in
# Note: there are some wells with no growth that could be removed here

# Blanks (PBS)
blank.col <- look.table %>%
  filter(media == "PBS") %>%
  pull(col)
blanks <- data.frame(time.h, data[, blank.col+1])
colnames(blanks)[1] <- "time"

# cDSM
cDSM.col <- look.table %>%
  filter(media == "cDSM") %>%
  pull(col)
#cDSM.remove <- c(13, 25,37)
#cDSM.col <- cDSM.col[!cDSM.col %in% cDSM.remove]
cDSM <- data.frame(time.h, data[, cDSM.col+1])
colnames(cDSM)[1] <- "time"

# LB
LB.col <- look.table %>%
  filter(media == "LB") %>%
  pull(col)
LB <- data.frame(time.h, data[, LB.col+1])
colnames(LB)[1] <- "time"

# R2B
R2B.col <- look.table %>%
  filter(media == "R2B") %>%
  pull(col)
R2B <- data.frame(time.h, data[, R2B.col+1])
colnames(R2B)[1] <- "time"

# DSM
DSM.col <- look.table %>%
  filter(media == "DSM") %>%
  pull(col)
DSM <- data.frame(time.h, data[, DSM.col+1])
colnames(DSM)[1] <- "time"
```


# Make figure

```{r}

# Following line initiate location to write file
png(filename ="~/Desktop/Fig.heat.png", width = 1200, height = 900, res = 96 * 2) 

# Start plot 
plot.new()

# Define plotting margins
par(mar = c(7, 7, 5, 7))

# Make plot for the first blank (PBS) replicate
plot(blanks[,1], blanks[,2], xlim = c(3, 70), 
     ylim = c(0, 210), type = "l", 
     lty = 1, col = "grey", lwd = 2, ylab = "", xlab = "", 
     cex.lab = 1.5, las = 1, yaxt = "n", xaxt = "n")

# Add lines for other blank replicates (color = grey)
# We just plotted column 2 and 1
# Now we plot column 3 and 1, and so forth
for(i in 3:ncol(blanks)) {
  lines(blanks[,1], blanks[,i], col = "grey")  
}

# Add cDSM lines
# this time plot column 2 and 1, and so forth
for(i in 2:ncol(cDSM)) {
  lines(cDSM[,1], cDSM[,i], col = "blue")  
}

# Add LB lines
for(i in 2:ncol(LB)) {
  lines(LB[,1], LB[,i], col = "green")  
}

# Add R2B lines
for(i in 2:ncol(R2B)) {
  lines(R2B[,1], R2B[,i], col = "red")  
}

# Add DSM lines
for(i in 2:ncol(DSM)) {
  lines(DSM[,1], DSM[,i], col = "black")  
}

# Add box around plot
box(lwd = 2)

# Add axis ticks and labels
axis(side = 2, lwd.ticks = 2, las = 1, cex.axis = 1.25, 
     labels = c("0", "50", "100", "150", "200"), at = c(0, 50, 100, 150, 200))

axis(side = 4, labels = F, lwd.ticks = 2, at = c(0, 50, 100, 150, 200))

axis(side = 1, lwd.ticks = 2, cex.axis = 1.25, las = 1, mgp = c(1, 1, 0),
    labels = c("10", "30", "60"), at = c(10, 30, 60))

axis(side = 3, labels = F, lwd.ticks = 2, las = 1, cex.axis = 1, 
   at = c(10, 30, 60))

# Add axis labels
mtext('Heat (μW)', side = 2, outer = TRUE, cex = 1.5, 
      line = -3.5, adj = 0.6)

mtext('Time (h)', side = 1, outer = TRUE, cex = 1.5, 
      line = -4, adj = 0.5)

# Add a legend
legend("topright", legend = c("blanks", "R2B", "cDSM", "DSM", "LB"), 
       col = c("grey", "red", "blue", "black", "green"), lty = 1, 
       cex = 0.75, bty = "n", bg = "transparent", seg.len = 1)

# Close plot device (completes writing of file)
dev.off()
graphics.off()

# Shows plot in R console window
img <- readPNG("~/Desktop/Fig.heat.png")
grid.raster(img)
```